version: '3.8'
services:
  ros-noetic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ee106_ros
    tty: true
    stdin_open: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
    network_mode: "host"
    volumes:
      - ./catkin_ws:/root/catkin_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    runtime: nvidia