// Generated by gencpp from file ee106s25/EE106lab_custom.msg
// DO NOT EDIT!


#ifndef EE106S25_MESSAGE_EE106LAB_CUSTOM_H
#define EE106S25_MESSAGE_EE106LAB_CUSTOM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ee106s25
{
template <class ContainerAllocator>
struct EE106lab_custom_
{
  typedef EE106lab_custom_<ContainerAllocator> Type;

  EE106lab_custom_()
    : header()
    , int_data(0)
    , float_data(0.0)
    , string_data()  {
    }
  EE106lab_custom_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , int_data(0)
    , float_data(0.0)
    , string_data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _int_data_type;
  _int_data_type int_data;

   typedef float _float_data_type;
  _float_data_type float_data;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _string_data_type;
  _string_data_type string_data;





  typedef boost::shared_ptr< ::ee106s25::EE106lab_custom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ee106s25::EE106lab_custom_<ContainerAllocator> const> ConstPtr;

}; // struct EE106lab_custom_

typedef ::ee106s25::EE106lab_custom_<std::allocator<void> > EE106lab_custom;

typedef boost::shared_ptr< ::ee106s25::EE106lab_custom > EE106lab_customPtr;
typedef boost::shared_ptr< ::ee106s25::EE106lab_custom const> EE106lab_customConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ee106s25::EE106lab_custom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ee106s25::EE106lab_custom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ee106s25::EE106lab_custom_<ContainerAllocator1> & lhs, const ::ee106s25::EE106lab_custom_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.int_data == rhs.int_data &&
    lhs.float_data == rhs.float_data &&
    lhs.string_data == rhs.string_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ee106s25::EE106lab_custom_<ContainerAllocator1> & lhs, const ::ee106s25::EE106lab_custom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ee106s25

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ee106s25::EE106lab_custom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ee106s25::EE106lab_custom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ee106s25::EE106lab_custom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ee106s25::EE106lab_custom_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ee106s25::EE106lab_custom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ee106s25::EE106lab_custom_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ee106s25::EE106lab_custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb75e96e5657d862c61a6395ce06cb0a";
  }

  static const char* value(const ::ee106s25::EE106lab_custom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb75e96e5657d862ULL;
  static const uint64_t static_value2 = 0xc61a6395ce06cb0aULL;
};

template<class ContainerAllocator>
struct DataType< ::ee106s25::EE106lab_custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee106s25/EE106lab_custom";
  }

  static const char* value(const ::ee106s25::EE106lab_custom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ee106s25::EE106lab_custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 int_data\n"
"float32 float_data\n"
"string string_data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ee106s25::EE106lab_custom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ee106s25::EE106lab_custom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.int_data);
      stream.next(m.float_data);
      stream.next(m.string_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EE106lab_custom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ee106s25::EE106lab_custom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ee106s25::EE106lab_custom_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "int_data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.int_data);
    s << indent << "float_data: ";
    Printer<float>::stream(s, indent + "  ", v.float_data);
    s << indent << "string_data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.string_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EE106S25_MESSAGE_EE106LAB_CUSTOM_H
