// Generated by gencpp from file ee106s25/EE106lab_custom_new.msg
// DO NOT EDIT!


#ifndef EE106S25_MESSAGE_EE106LAB_CUSTOM_NEW_H
#define EE106S25_MESSAGE_EE106LAB_CUSTOM_NEW_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ee106s25
{
template <class ContainerAllocator>
struct EE106lab_custom_new_
{
  typedef EE106lab_custom_new_<ContainerAllocator> Type;

  EE106lab_custom_new_()
    : header()
    , int_rand1(0)
    , int_rand2(0)  {
    }
  EE106lab_custom_new_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , int_rand1(0)
    , int_rand2(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _int_rand1_type;
  _int_rand1_type int_rand1;

   typedef int32_t _int_rand2_type;
  _int_rand2_type int_rand2;





  typedef boost::shared_ptr< ::ee106s25::EE106lab_custom_new_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ee106s25::EE106lab_custom_new_<ContainerAllocator> const> ConstPtr;

}; // struct EE106lab_custom_new_

typedef ::ee106s25::EE106lab_custom_new_<std::allocator<void> > EE106lab_custom_new;

typedef boost::shared_ptr< ::ee106s25::EE106lab_custom_new > EE106lab_custom_newPtr;
typedef boost::shared_ptr< ::ee106s25::EE106lab_custom_new const> EE106lab_custom_newConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ee106s25::EE106lab_custom_new_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ee106s25::EE106lab_custom_new_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ee106s25::EE106lab_custom_new_<ContainerAllocator1> & lhs, const ::ee106s25::EE106lab_custom_new_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.int_rand1 == rhs.int_rand1 &&
    lhs.int_rand2 == rhs.int_rand2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ee106s25::EE106lab_custom_new_<ContainerAllocator1> & lhs, const ::ee106s25::EE106lab_custom_new_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ee106s25

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ee106s25::EE106lab_custom_new_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ee106s25::EE106lab_custom_new_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ee106s25::EE106lab_custom_new_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ee106s25::EE106lab_custom_new_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ee106s25::EE106lab_custom_new_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ee106s25::EE106lab_custom_new_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ee106s25::EE106lab_custom_new_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e647cd8bb535d6620f5f963b21085c3";
  }

  static const char* value(const ::ee106s25::EE106lab_custom_new_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e647cd8bb535d66ULL;
  static const uint64_t static_value2 = 0x20f5f963b21085c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ee106s25::EE106lab_custom_new_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee106s25/EE106lab_custom_new";
  }

  static const char* value(const ::ee106s25::EE106lab_custom_new_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ee106s25::EE106lab_custom_new_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 int_rand1\n"
"int32 int_rand2\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ee106s25::EE106lab_custom_new_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ee106s25::EE106lab_custom_new_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.int_rand1);
      stream.next(m.int_rand2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EE106lab_custom_new_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ee106s25::EE106lab_custom_new_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ee106s25::EE106lab_custom_new_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "int_rand1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.int_rand1);
    s << indent << "int_rand2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.int_rand2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EE106S25_MESSAGE_EE106LAB_CUSTOM_NEW_H
